pierre-nygard/GroupA_Backend

HorrorMovieAPI/Models/Casting.cs
HorrorMovieAPI/Models/CastingDTO.cs
HorrorMovieAPI/Models/Director.cs
HorrorMovieAPI/Models/DirectorDTO.cs
HorrorMovieAPI/Models/Movie.cs
HorrorMovieAPI/Models/MovieDTO.cs

@andremorad

---

HorrorMovieAPI/Services/IMovieRepository.cs

SKRAC-74 Completed

---

.gitignore

SKRAC-79 updated gitignore

---

HorrorMovieAPI/Documentation/standups.md

Fixed formation in Standups document

---

HorrorMovieAPI/Services/DirectorRepository.cs

Created DirectorRepository

---

HorrorMovieAPI/Services/DirectorRepository.cs

added IDirectorRepository to my DirectorRepository

Fixed DirectorRepository

---

HorrorMovieAPI/Controllers/DirectorController.cs

Added the conroller and
dependency inversion for DirectorController

Created DirectorController

---

HorrorMovieAPI/Services/IActorRepository.cs

Added the metods to IActorRepository.

Created IActorRepository

---

HorrorMovieAPI/Services/ActorRepository.cs

Created ActorRepository

---

HorrorMovieAPI/Services/GenreRepository.cs

Created GenreRepository

---

HorrorMovieAPI/Services/IRepository.cs

tog bort remove  och la till Save

SKRAC-86 add save remove get all

---

HorrorMovieAPI/Controllers/IControllerCRUD.cs

Created IControllerCRUD

---

HorrorMovieAPI/Services/Repository.cs

Created Repository.cs Get(int id)

---

HorrorMovieAPI/Controllers/ControllerCRUD.cs

Created a constructor to ControllerCRUD

---

HorrorMovieAPI/Services/Repository.cs

Created Repository.cs Update(T entity)

---

HorrorMovieAPI/Controllers/ControllerCRUD.cs

Created a dependency injection to ControllerCRUD

---

HorrorMovieAPI/Controllers/ControllerCRUD.cs

Created ControllerCRUD Get(id)

---

HorrorMovieAPI/Controllers/MoviesController.cs

Created Add Method GetAll() to MovieController

---

HorrorMovieAPI/Controllers/ControllerCRUD.cs

SKRACK-96 is made

---

HorrorMovieAPI.Tests/HorrorMovieAPI.Tests.csproj
HorrorMovieAPI.Tests/UnitTest1.cs
HorrorMovieAPI/Controllers/DirectorsController.cs

Tested DirectorsController GetAll() without content

Created DirectorsConroller Test

---

HorrorMovieAPI/Configuration/MappedProfile.cs
HorrorMovieAPI/Startup.cs

Created MappedProfile.cs

---

HorrorMovieAPI/Controllers/GenresController.cs

Created a mapper for GenresController and Implement mapper for Dependency injection

Created a mapper for GenresController

---

HorrorMovieAPI/Controllers/GenresController.cs

Created Method GetById(int id) in GenresController

---

HorrorMovieAPI/Services/IMovieRepository.cs
HorrorMovieAPI/Services/MovieRepository.cs

Created MovieRepository and IMovieRepository method GetById(int id)

---

HorrorMovieAPI/Configuration/MappedProfile.cs
HorrorMovieAPI/Controllers/ActorsController.cs
HorrorMovieAPI/Dto/ActorForUpdateDTO.cs
HorrorMovieAPI/Services/IRepository.cs
HorrorMovieAPI/Services/Repository.cs

Ignore last pull request (SKRAC-147), had the wrong branch name for some reason.

Finished with CRUD functionality and full HATEOAS in ActorsController.

---

HorrorMovieAPI/Configuration/MappedProfile.cs
HorrorMovieAPI/Controllers/MoviesController.cs
HorrorMovieAPI/Dto/MovieToCreateDTO.cs
HorrorMovieAPI/Services/Repository.cs

SKRAC-127 

---

HorrorMovieAPI.Tests/ControllerTests/ActorControllerTests.cs
HorrorMovieAPI.Tests/ControllerTests/DirectorControllerTests.cs
HorrorMovieAPI.Tests/ControllerTests/GenreControllerTests.cs
HorrorMovieAPI.Tests/ControllerTests/MovieControllerTest.cs
HorrorMovieAPI.Tests/RepositoryTests/ActorRepositoryTests.cs
HorrorMovieAPI.Tests/RepositoryTests/DirectorRepositoryTests.cs
HorrorMovieAPI.Tests/RepositoryTests/GenreRepositoryTests.cs
HorrorMovieAPI/Controllers/ActorsController.cs
HorrorMovieAPI/Controllers/DirectorsController.cs
HorrorMovieAPI/Controllers/GenresController.cs
HorrorMovieAPI/Controllers/MoviesController.cs
HorrorMovieAPI/HorrorMovieAPI.xml
HorrorMovieAPI/Services/ActorRepository.cs
HorrorMovieAPI/Services/DirectorRepository.cs
HorrorMovieAPI/Services/GenreRepository.cs
HorrorMovieAPI/Services/IActorRepository.cs
HorrorMovieAPI/Services/IDirectorRepository.cs
HorrorMovieAPI/Services/IGenreRepository.cs
HorrorMovieAPI/Services/IMovieRepository.cs
HorrorMovieAPI/Services/IRepository.cs
HorrorMovieAPI/Services/MovieRepository.cs
HorrorMovieAPI/Services/Repository.cs

We also fixed some unit tests.

Changed Implementation/References of Generic Repository.
